name: Publish apps
run-name: ${{ github.actor }} is publishing projects to dev 🚀
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): dev, prod"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
      app:
        description: "App to publish (one of): public, web"
        required: true
        default: "public"
        type: choice
        options:
          - public
          - web
  workflow_call:
    inputs:
      release-type:
        default: "dev"
        type: string
      app:
        default: "public"
        type: string
jobs:
  publish_dev:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Run a publish script
        if: github.event.inputs.app == 'public'
        run: ssh ubuntu "cd ~/frontend/deployment/upwithcrowd/${{ github.event.inputs.release-type }} && chmod 777 ./publish-cli.sh && ./publish-cli.sh --app public --port 1460"
      - name: Run a publish script for web
        if: github.event.inputs.app == 'web'
        run: ssh ubuntu "cd ~/frontend/deployment/upwithcrowd/${{ github.event.inputs.release-type }} && chmod 777 ./publish-cli.sh && ./publish-cli.sh --app web --port 1461"
