name: Publish dev websites
run-name: ${{ github.actor }} is publishing projects to dev 🚀
on:
  push:
    branches: [main, master]
jobs:
  publish_dev:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Run a publish script
        run: ssh ubuntu "cd ~/frontend/upwithcrowd/dev && chmod 777 ./publish-cli.sh && ./publish-cli.sh --app public --port 1460"
